name: Terraform CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  terraform:
    name: 'Terraform Lint, Security Check, and Deploy'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'ap-south-1'

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Install TFLint'
      run: |
        latest_version=$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | jq -r .tag_name)
        curl -sLo tflint.zip https://github.com/terraform-linters/tflint/releases/download/${latest_version}/tflint_linux_amd64.zip
        unzip tflint.zip -d /usr/local/bin/
        tflint --version

    #- name: 'Install tfsec'
    #run: |
     #   latest_version=$(curl -s https://api.github.com/repos/aquasecurity/tfsec/releases/latest | jq -r .tag_name)
     #   curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/${latest_version}/tfsec-linux-amd64
     #   chmod +x tfsec
     #   mv tfsec /usr/local/bin/
      #  tfsec --version

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Format'
      run: terraform fmt

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'TFLint'
      run: |
        tflint --init
        tflint

    #- name: 'tfsec'
     # run: tfsec .

    - name: 'Terraform Plan'
      id: plan
      run: |
        terraform plan -out=tfplan
        aws s3 cp tfplan s3://terraformplan223/tfplan

    - name: 'Download Terraform Plan from S3'
      if: github.ref == 'refs/heads/main'
      run: aws s3 cp s3://terraformplan223/tfplan tfplan

    - name: 'Terraform Apply'
      if: github.ref == 'refs/heads/dev'
      run: terraform apply -auto-approve tfplan
